kapibara-tornado/frontend-app

- netlify.toml
> netlifyのtoml追加

- src/app/page.tsx
- src/components/features/HamburgerMenu.tsx
・ナビゲーション作成
・Homeと診断結果一覧にページを飛ぶようにした
> add:ナビゲーション

- src/app/data/questions.ts
- src/app/page.tsx
- src/app/play/page.tsx
- src/app/result/page.tsx
- src/components/features/BackgroundImage.tsx
- src/lib/Cookie/client.ts
- src/lib/Cookie/server.ts
- src/types/types.ts
- src/usecases/useQuestions.ts
- src/usecases/useResult.ts
- src/utils/getMBTIId.ts
> scoresからどの政治家に近いかを判定する処理を追加

- netlify.toml
> netlifyの設定書き換え

- netlify.toml
- src/app/page.tsx
#52 
ホームページのデザイン変更(モバイルサイズ、PCサイズ)
| モバイル | PC |
| --- | --- |
| <img alt="image" src="https://github.com/user-attachments/assets/239b54ca-aac2-4e17-8f1f-233187752b1a"> |<img alt="image" src="https://github.com/user-attachments/assets/6679cc8b-12be-4421-abeb-25f3718d1ddb"> |
画像の変更はこのIssueでは未対応
> ホームページのデザインの変更

- .env.exapmle
- src/app/page.tsx
- src/app/result/page.tsx
- src/components/features/Loader/index.tsx
> プレイスタートの当たり判定

- src/app/result/page.tsx
- src/components/features/SimilarPoliticianCard.tsx
- src/components/features/TypeCard.tsx
#66 
| モバイル | PC |
| --- | --- |
| <img width="543" alt="image" src="https://github.com/user-attachments/assets/58189330-b768-4554-ac94-cbe8e976550c"> | <img width="1512" alt="image" src="https://github.com/user-attachments/assets/8893f73b-a1b5-465d-a603-e7ff944d15a2"> |
> 診断結果のレスポンシブ対応

- src/components/features/BackgroundImage.tsx
- src/components/features/HamburgerMenu.tsx
> 結果画面で背景をスクロールさせないようにする

- src/app/result/page.tsx
> add: 診断結果の詳細へのリンク作成

- src/app/listresult/page.tsx
> add: responsive listresult

- src/app/data/resultDetail.ts
- src/components/features/ResultDetailArea.tsx
- src/components/features/ScoreBar.tsx
#9 
診断結果詳細画面のページによってスコアバーの色を変更
〜型の表記
> add: color scorebar

- src/utils/getMBTIId.ts
> [最新]MBTIid修正

- src/app/data/questions.ts
- src/app/play/page.tsx
- src/types/types.ts
- src/usecases/useQuestions.ts
> 質問画面変更-レビュー修正-

- src/app/data/resultDetail.ts
- src/components/features/ScoreBar.tsx
- src/components/features/SimpleSlider/index.tsx
- src/components/features/SimpleSlider/logics/index.ts
#89 
・スコアバーの修正
・67%のリベラル型などの型をE,P,A,S,C,L,N,Iに対応
> 詳細画面修正-レビュー修正-

- src/app/play/page.tsx
#8 
play画面で、good/badボタンを押した際のアニメーションの追加
> playでのアニメーション

- src/app/data/resultDetail.ts
- src/components/features/ResultDetailArea.tsx
- src/components/features/ScoreBar.tsx
- src/components/features/SimpleSlider/index.tsx
> 診断結果詳細画面のレスポンシブ対応

- src/app/page.tsx
- src/app/result/detail/page.tsx
- src/app/result/list/page.tsx
- src/app/result/page.tsx
- src/app/result/printer/page.tsx
- src/components/features/HamburgerMenu.tsx
- src/components/features/Header/index.tsx
- src/components/features/ResultNothing/index.tsx
- src/usecases/useCookie.ts
- 結果がない時の画面
- ナビゲーションのcookie取得仕様の修正
- ホームページのデザイン修正
- bgimageのpropsのwaringエラー修正
> 結果がない時の画面および諸々修正

- src/app/data/questions.ts
> change: 質問文の語尾を変える

- src/components/features/SimilarPoliticianCard.tsx
- src/components/features/TypeCard.tsx
> change: 診断結果のデザイン

- src/app/play/page.tsx
#126
スワイプのアニメーションが良くないので、PCの方のアニメーションは消しておく。
> playでのアニメーションをモバイルだけにする
